/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.debuglevel.greetlib

import kotlin.test.Test
import kotlin.test.assertTrue

class BookGeneratorTests {
    @Test
    fun testSomeLibraryMethod() {
        val test = BookGenerator.generate("test").content
        assertTrue(test.contains("bla test"))
    }
}
