/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.debuglevel.greetlib

import io.micronaut.context.ApplicationContext

object BookGenerator {
    fun generate(title: String): Book {

        ApplicationContext.run().use { context ->
            val myBean = context.getBean(BookService::class.java)
            val newTitle = myBean.formatTitle(title)
            return Book(title, "$newTitle bla")
        }
    }
}
