/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.debuglevel.greetlib

object BookGenerator {
    fun generate(title: String): Book {
        return Book(title, "bla $title bla $title bla")
    }
}
